In [1]:
import string
from unittest.mock import inplace

import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from pygments.styles.dracula import background
from sklearn.conftest import pytest_generate_tests

In [2]:
data=pd.read_csv('spam.csv',encoding='latin-1')
data.sample(10)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
4382,ham,No need lar i go engin? Cos my sis at arts tod...,NaN,NaN,NaN
5349,ham,I'm home...,NaN,NaN,NaN
5069,spam,5p 4 alfie Moon's Children in need song on ur ...,NaN,NaN,NaN
4687,ham,Hmmm.but you should give it on one day..,NaN,NaN,NaN
3280,ham,I tot it's my group mate... Lucky i havent rep...,NaN,NaN,NaN
4434,spam,Don't b floppy... b snappy & happy! Only gay c...,NaN,NaN,NaN
2971,ham,Sary just need Tim in the bollox &it hurt him ...,NaN,NaN,NaN
5293,ham,I donno its in your genes or something,NaN,NaN,NaN
4286,ham,I wud never mind if u dont miss me or if u don...,NaN,NaN,NaN
3336,ham,I AM AT THE GAS STATION. GO THERE.,NaN,NaN,NaN


In [3]:
data.info()
data=data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str  
 1   v2          5572 non-null   str  
 2   Unnamed: 2  50 non-null     str  
 3   Unnamed: 3  12 non-null     str  
 4   Unnamed: 4  6 non-null      str  
dtypes: str(5)
memory usage: 217.8 KB


,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [4]:
data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [5]:
data['target'].unique()

<StringArray>
['ham', 'spam']
Length: 2, dtype: str

In [6]:
data['target']=data['target'].map({'ham':0,'spam':1})

In [9]:
data.head()

,target,text
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [7]:
data.isna().sum()

target    0
text      0
dtype: int64

In [8]:
#Checking duplicates
data.duplicated().sum()

np.int64(403)

In [9]:
data=data.drop_duplicates(keep='first')
data.shape

(5169, 2)

In [16]:
#EDA
!pip install matplotlib


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.1 MB 16.8 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 21.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 19.7 MB/s  0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 14.8 MB/s  0:00:00

   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   --------------


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
# cnt=data['target'].value_counts()
# percentage=(cnt/(len(cnt)))*100
# plot=data['target'].value_counts(normalize=True).plot(kind='bar')
# for ind,val in enumerate(percentage):
#     plot.text(ind,cnt.values[ind]+0.1,f"{val:.2f}%",ha='center')
# plt.show()
cnt = data['target'].value_counts()
percentage = cnt / len(data) * 100

ax = cnt.plot(kind='bar')

for i, v in enumerate(cnt):
    ax.text(i, v + 0.1, f"{percentage.iloc[i]:.2f}%", ha='center')

plt.title("Target Distribution")
plt.xlabel("Target")
plt.ylabel("Count")

plt.show()


In [11]:
import matplotlib.pyplot as plt
plt.pie(cnt,labels=['not spam','spam'],autopct='%0.2f')
plt.show()

In [22]:
!pip install nltk


   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------- ----- 1.3/1.5 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 10.8 MB/s  0:00:00

   ------------- -------------------------- 1/3 [click]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]




[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
data['num_char']=data['text'].apply(len)
data.head()

,target,text,num_char
0,0,"Go until jurong point, crazy.. Available only ...",111
1,0,Ok lar... Joking wif u oni...,29
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155
3,0,U dun say so early hor... U c already then say...,49
4,0,"Nah I don't think he goes to usf, he lives aro...",61


In [16]:
data['num_words']=data['text'].apply(lambda x:len(nltk.word_tokenize(x)))
data.head()

,target,text,num_char,num_words
0,0,"Go until jurong point, crazy.. Available only ...",111,24
1,0,Ok lar... Joking wif u oni...,29,8
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37
3,0,U dun say so early hor... U c already then say...,49,13
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15


In [17]:
data['num_sen']=data['text'].apply(lambda x:len(nltk.sent_tokenize(x)))
data.head()

,target,text,num_char,num_words,num_sen
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2
1,0,Ok lar... Joking wif u oni...,29,8,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2
3,0,U dun say so early hor... U c already then say...,49,13,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1


In [18]:
#For not spam
data[data['target']==0][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,4516.000000,4516.000000,4516.000000
mean,70.459256,17.123782,1.820195
std,56.358207,13.493970,1.383657
min,2.000000,1.000000,1.000000
25%,34.000000,8.000000,1.000000
50%,52.000000,13.000000,1.000000
75%,90.000000,22.000000,2.000000
max,910.000000,220.000000,38.000000


In [19]:
#For spam
data[data['target']==1][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,653.000000,653.000000,653.000000
mean,137.891271,27.667688,2.970904
std,30.137753,7.008418,1.488425
min,13.000000,2.000000,1.000000
25%,132.000000,25.000000,2.000000
50%,149.000000,29.000000,3.000000
75%,157.000000,32.000000,4.000000
max,224.000000,46.000000,9.000000


In [38]:
!pip install seaborn


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
import seaborn as sns
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_words'],color='green')
sns.histplot(data[data['target']==1]['num_words'],color='red')

plt.show()

In [21]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_char'],color='green')
sns.histplot(data[data['target']==1]['num_char'],color='red')
plt.show()

In [22]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_sen'],color='green')
sns.histplot(data[data['target']==1]['num_sen'],color='red')
plt.show()

In [23]:
sns.heatmap(data[['target','num_char','num_words','num_sen']].corr(),annot=True)
plt.show()

Text Preprocessing

In [24]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [25]:
import string
def text_tranform(text):
    text=text.lower()
    text=nltk.word_tokenize(text)
    res=[]
    for i in text:
        if i.isalnum():
            res.append(i)
    text=res[:]
    res.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            res.append(i)
    text=res[:]
    res.clear()
    for i in text:
        res.append(ps.stem(i))
    return ' '.join(res)

In [26]:
data['transformed_text']=data['text'].apply(text_tranform)

In [27]:
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2,go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,29,8,2,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,49,13,1,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1,nah think goe usf live around though


In [86]:
!pip install wordcloud


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
from wordcloud import WordCloud
wc=WordCloud(width=1000,height=1000,background_color='beige')


In [29]:
spam_wc=wc.generate(data[data['target']==0]['transformed_text'].str.cat(sep=" "))

In [30]:
plt.imshow(spam_wc)
plt.show()

In [31]:
ham_wc=wc.generate(data[data['target']==1]['transformed_text'].str.cat(sep=" "))

In [33]:
plt.imshow(ham_wc)
plt.show()

In [60]:
from collections import Counter
ham_corpus=[]
for sen in data[data['target']==0]['transformed_text'].to_list():
    for word in sen.split():
        ham_corpus.append(word)
word_count=Counter(ham_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='magma',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

In [61]:
spam_corpus=[]
for sen in data[data['target']==1]['transformed_text'].to_list():
    for word in sen.split():
        spam_corpus.append(word)
word_count=Counter(spam_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='flare',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

Model

In [88]:
#Using bag of words vectorization method
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer()
tfidf=TfidfVectorizer(max_features=3000)

In [89]:
X=tfidf.fit_transform(data['transformed_text']).toarray()
X.shape

(5169, 3000)

In [90]:
Y=data['target'].values
Y

array([0, 0, 1, ..., 0, 0, 0], shape=(5169,))

In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [92]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix
gn=GaussianNB()
mn=MultinomialNB()
bn=BernoulliNB()


In [93]:
gn.fit(X_train,Y_train)
y_pred1=gn.predict(X_test)
print(accuracy_score(Y_test,y_pred1))
print(precision_score(Y_test,y_pred1))
print(confusion_matrix(Y_test,y_pred1))


0.874274661508704
0.5181818181818182
[[790 106]
 [ 24 114]]


In [94]:
mn.fit(X_train,Y_train)
y_pred2=mn.predict(X_test)
print(accuracy_score(Y_test,y_pred2))
print(precision_score(Y_test,y_pred2))
print(confusion_matrix(Y_test,y_pred2))


0.9709864603481625
1.0
[[896   0]
 [ 30 108]]


In [95]:
bn.fit(X_train,Y_train)
y_pred3=bn.predict(X_test)
print(accuracy_score(Y_test,y_pred3))
print(precision_score(Y_test,y_pred3))
print(confusion_matrix(Y_test,y_pred3))


0.9835589941972921
0.991869918699187
[[895   1]
 [ 16 122]]


In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [97]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Gaussian NB": GaussianNB(),
    "Multinomial NB": MultinomialNB(),
    "Bernoulli NB": BernoulliNB(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Extra Trees": ExtraTreesClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC()
}
def train_model(model, X_train, Y_train, X_test, Y_test):

    model.fit(X_train, Y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(Y_test, y_pred)
    prec = precision_score(Y_test, y_pred)

    return acc, prec
accuracy_scores = []
precision_scores = []
model_names = []

for name, model in models.items():

    acc, prec = train_model(model, X_train, Y_train, X_test, Y_test)

    model_names.append(name)
    accuracy_scores.append(acc)
    precision_scores.append(prec)
    results = pd.DataFrame({
    "Model": model_names,
    "Accuracy": accuracy_scores,
    "Precision": precision_scores
})

results.sort_values(by="Precision", ascending=False)

,Model,Accuracy,Precision
2,Multinomial NB,0.970986,1.000000
9,KNN,0.905222,1.000000
3,Bernoulli NB,0.983559,0.991870
10,SVC,0.973888,0.982609
0,Logistic Regression,0.954545,0.978947
6,Extra Trees,0.976789,0.975000
5,Random Forest,0.973888,0.974359
8,Gradient Boosting,0.958414,0.943925
7,AdaBoost,0.921663,0.820225
4,Decision Tree,0.948743,0.797203


In [98]:
import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(mn,open('model.pkl','wb'))