In [2]:
import string
from unittest.mock import inplace

import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from pygments.styles.dracula import background
from sklearn.conftest import pytest_generate_tests

In [3]:
data=pd.read_csv('spam.csv',encoding='latin-1')
data.sample(10)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
4375,spam,"If you don't, your prize will go to another cu...",NaN,NaN,NaN
3459,ham,I am back. Bit long cos of accident on a30. Ha...,NaN,NaN,NaN
5040,ham,She ran off with a younger man. we will make p...,NaN,NaN,NaN
4659,ham,You call him and tell now infront of them. Cal...,NaN,NaN,NaN
1329,ham,I dont know what to do to come out of this so ...,NaN,NaN,NaN
3252,ham,K:)k..its good:)when are you going?,NaN,NaN,NaN
1036,ham,"No my blankets are sufficient, thx",NaN,NaN,NaN
754,ham,Realy sorry-i don't recognise this number and ...,NaN,NaN,NaN
3652,ham,It has issues right now. Ill fix for her by to...,NaN,NaN,NaN
2717,ham,Okie.. Thanx..,NaN,NaN,NaN


In [4]:
data.info()
data=data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [5]:
data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [6]:
data['target'].unique()

array(['ham', 'spam'], dtype=object)

In [7]:
data['target']=data['target'].map({'ham':0,'spam':1})

In [8]:
data.head()

,target,text
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [9]:
new_spam = [
"Congratulations! You have won a brand new car. Claim now.",
"Lucky draw winner! You just won ₹5,00,000. Call now.",
"You have been selected for a free iPhone. Click here.",
"Urgent! Your bank account will be blocked. Verify now.",
"Get instant loan approval with zero documents. Apply today.",
"You won a holiday package to Goa. Claim your prize now.",
"Limited offer! Recharge now and get 50% cashback.",
"Your number has won a lottery of ₹10 lakh.",
"Act fast! Exclusive deal ends today. Click here.",
"Claim your free gift voucher worth ₹2000 now.",

"Dear user, your KYC is pending. Update immediately.",
"You have won a lucky draw. Send your details to claim.",
"Get guaranteed job placement. Register now.",
"Win exciting prizes by participating today.",
"You are selected for a premium credit card. Apply now.",
"Earn ₹5000 daily from home. No experience required.",
"Get rich quickly with this simple trick. Join now.",
"Exclusive offer! Buy now and save big.",
"Your SIM will be deactivated. Verify your details now.",
"You won a surprise gift. Click to claim.",

"Free recharge for selected users. Claim now.",
"You are eligible for a personal loan. Apply instantly.",
"Claim your cashback reward before it expires.",
"Limited seats available. Register now.",
"You have been chosen for a special reward.",
"Urgent notice: update your bank details immediately.",
"Win a brand new bike. Participate now.",
"Your account has suspicious activity. Verify now.",
"Get 100% bonus on your first deposit.",
"Exclusive deal just for you. Click now.",

"Congratulations! You are our lucky winner.",
"Claim your prize money now by clicking the link.",
"You have won free movie tickets. Book now.",
"Get instant approval for your credit card.",
"Special offer! Buy one get one free.",
"Hurry! Offer valid for today only.",
"You have received a gift. Claim it now.",
"Earn money online easily. Join today.",
"Your ATM card will be blocked. Update now.",
"You won a cash prize. Contact immediately.",

"Free entry into lucky draw. Register now.",
"You are selected for a cash reward.",
"Claim your free subscription now.",
"You have been pre-approved for a loan.",
"Win big prizes with this limited offer.",
"Your mobile number has won a jackpot.",
"Urgent: confirm your account details now.",
"Get exclusive discounts on your next purchase.",
"You have been shortlisted. Pay registration fee now.",
"Act now to claim your exciting reward."
]

In [10]:
new_df=pd.DataFrame({
    'text':new_spam,
    'target':[1]*len(new_spam)
})

In [15]:
data=pd.concat([data,new_df],ignore_index=True)
data=data.sample(frac=1,random_state=42).reset_index(drop=True)
data.tail(10)

,target,text
5762,0,I dont know oh. Hopefully this month.
5763,0,Omg you can make a wedding chapel in frontierv...
5764,1,You won a surprise gift. Click to claim.
5765,1,Get guaranteed job placement. Register now.
5766,0,Anything...
5767,0,Lol! U drunkard! Just doing my hair at d momen...
5768,0,Thank u!
5769,0,K..u also dont msg or reply to his msg..
5770,0,Ho ho - big belly laugh! See ya tomo
5771,0,THANX 4 PUTTIN DA FONE DOWN ON ME!!


In [16]:
data.isna().sum()

target    0
text      0
dtype: int64

In [17]:
#Checking duplicates
data.duplicated().sum()

np.int64(553)

In [18]:
data=data.drop_duplicates(keep='first')
data.shape

(5219, 2)

In [16]:
#EDA
!pip install matplotlib


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.1 MB 16.8 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 21.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 19.7 MB/s  0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 14.8 MB/s  0:00:00

   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   --------------


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
# cnt=data['target'].value_counts()
# percentage=(cnt/(len(cnt)))*100
# plot=data['target'].value_counts(normalize=True).plot(kind='bar')
# for ind,val in enumerate(percentage):
#     plot.text(ind,cnt.values[ind]+0.1,f"{val:.2f}%",ha='center')
# plt.show()
cnt = data['target'].value_counts()
percentage = cnt / len(data) * 100

ax = cnt.plot(kind='bar')

for i, v in enumerate(cnt):
    ax.text(i, v + 0.1, f"{percentage.iloc[i]:.2f}%", ha='center')

plt.title("Target Distribution")
plt.xlabel("Target")
plt.ylabel("Count")

plt.show()


In [21]:
import matplotlib.pyplot as plt
plt.pie(cnt,labels=['not spam','spam'],autopct='%0.2f')
plt.show()

In [22]:
!pip install nltk


   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------- ----- 1.3/1.5 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 10.8 MB/s  0:00:00

   ------------- -------------------------- 1/3 [click]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]




[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
data['num_char']=data['text'].apply(len)
data.head()

,target,text,num_char
0,0,Lol u still feeling sick?,25
1,0,That means get the door,23
2,0,I was up all night too worrying about this app...,133
3,0,India have to take lead:),25
4,0,I don't run away frm u... I walk slowly &amp; ...,96


In [24]:
data['num_words']=data['text'].apply(lambda x:len(nltk.word_tokenize(x)))
data.head()

,target,text,num_char,num_words
0,0,Lol u still feeling sick?,25,6
1,0,That means get the door,23,5
2,0,I was up all night too worrying about this app...,133,30
3,0,India have to take lead:),25,7
4,0,I don't run away frm u... I walk slowly &amp; ...,96,27


In [25]:
data['num_sen']=data['text'].apply(lambda x:len(nltk.sent_tokenize(x)))
data.head()

,target,text,num_char,num_words,num_sen
0,0,Lol u still feeling sick?,25,6,1
1,0,That means get the door,23,5,1
2,0,I was up all night too worrying about this app...,133,30,2
3,0,India have to take lead:),25,7,1
4,0,I don't run away frm u... I walk slowly &amp; ...,96,27,2


In [26]:
#For not spam
data[data['target']==0][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,4516.000000,4516.000000,4516.000000
mean,70.459256,17.123782,1.820195
std,56.358207,13.493970,1.383657
min,2.000000,1.000000,1.000000
25%,34.000000,8.000000,1.000000
50%,52.000000,13.000000,1.000000
75%,90.000000,22.000000,2.000000
max,910.000000,220.000000,38.000000


In [27]:
#For spam
data[data['target']==1][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,703.000000,703.000000,703.000000
mean,131.261735,26.376956,2.883357
std,37.705559,8.222087,1.477483
min,13.000000,2.000000,1.000000
25%,121.000000,23.000000,2.000000
50%,147.000000,28.000000,3.000000
75%,157.000000,32.000000,4.000000
max,224.000000,46.000000,9.000000


In [38]:
!pip install seaborn


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
import seaborn as sns
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_words'],color='green')
sns.histplot(data[data['target']==1]['num_words'],color='red')

plt.show()

In [29]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_char'],color='green')
sns.histplot(data[data['target']==1]['num_char'],color='red')
plt.show()

In [30]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_sen'],color='green')
sns.histplot(data[data['target']==1]['num_sen'],color='red')
plt.show()

In [31]:
sns.heatmap(data[['target','num_char','num_words','num_sen']].corr(),annot=True)
plt.show()

Text Preprocessing

In [32]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [33]:
import string
def text_tranform(text):
    text=text.lower()
    text=nltk.word_tokenize(text)
    res=[]
    for i in text:
        if i.isalnum():
            res.append(i)
    text=res[:]
    res.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            res.append(i)
    text=res[:]
    res.clear()
    for i in text:
        res.append(ps.stem(i))
    return ' '.join(res)

In [34]:
data['transformed_text']=data['text'].apply(text_tranform)

In [35]:
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,Lol u still feeling sick?,25,6,1,lol u still feel sick
1,0,That means get the door,23,5,1,mean get door
2,0,I was up all night too worrying about this app...,133,30,2,night worri appt shame miss girl night quizz p...
3,0,India have to take lead:),25,7,1,india take lead
4,0,I don't run away frm u... I walk slowly &amp; ...,96,27,2,run away frm u walk slowli amp kill u care eno...


In [86]:
!pip install wordcloud


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [36]:
from wordcloud import WordCloud
wc=WordCloud(width=1000,height=1000,background_color='beige')


In [37]:
spam_wc=wc.generate(data[data['target']==0]['transformed_text'].str.cat(sep=" "))

In [38]:
plt.imshow(spam_wc)
plt.show()

In [39]:
ham_wc=wc.generate(data[data['target']==1]['transformed_text'].str.cat(sep=" "))

In [40]:
plt.imshow(ham_wc)
plt.show()

In [41]:
from collections import Counter
ham_corpus=[]
for sen in data[data['target']==0]['transformed_text'].to_list():
    for word in sen.split():
        ham_corpus.append(word)
word_count=Counter(ham_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='magma',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

In [42]:
spam_corpus=[]
for sen in data[data['target']==1]['transformed_text'].to_list():
    for word in sen.split():
        spam_corpus.append(word)
word_count=Counter(spam_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='flare',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

Model

In [43]:
#Using bag of words vectorization method
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer()
tfidf=TfidfVectorizer(ngram_range=(1,2),max_features=3000)

In [44]:
X=tfidf.fit_transform(data['transformed_text']).toarray()
X.shape

(5219, 3000)

In [45]:
Y=data['target'].values
Y

array([0, 0, 0, ..., 0, 0, 0], shape=(5219,))

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [47]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix
gn=GaussianNB()
mn=MultinomialNB()
bn=BernoulliNB()


In [48]:
gn.fit(X_train,Y_train)
y_pred1=gn.predict(X_test)
print(accuracy_score(Y_test,y_pred1))
print(precision_score(Y_test,y_pred1))
print(confusion_matrix(Y_test,y_pred1))


0.8649425287356322
0.5
[[774 129]
 [ 12 129]]


In [49]:
mn.fit(X_train,Y_train)
y_pred2=mn.predict(X_test)
print(accuracy_score(Y_test,y_pred2))
print(precision_score(Y_test,y_pred2))
print(confusion_matrix(Y_test,y_pred2))


0.9741379310344828
0.9830508474576272
[[901   2]
 [ 25 116]]


In [50]:
bn.fit(X_train,Y_train)
y_pred3=bn.predict(X_test)
print(accuracy_score(Y_test,y_pred3))
print(precision_score(Y_test,y_pred3))
print(confusion_matrix(Y_test,y_pred3))


0.9798850574712644
0.9918032786885246
[[902   1]
 [ 20 121]]


In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [52]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Gaussian NB": GaussianNB(),
    "Multinomial NB": MultinomialNB(),
    "Bernoulli NB": BernoulliNB(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Extra Trees": ExtraTreesClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC()
}
def train_model(model, X_train, Y_train, X_test, Y_test):

    model.fit(X_train, Y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(Y_test, y_pred)
    prec = precision_score(Y_test, y_pred)

    return acc, prec
accuracy_scores = []
precision_scores = []
model_names = []

for name, model in models.items():

    acc, prec = train_model(model, X_train, Y_train, X_test, Y_test)

    model_names.append(name)
    accuracy_scores.append(acc)
    precision_scores.append(prec)
    results = pd.DataFrame({
    "Model": model_names,
    "Accuracy": accuracy_scores,
    "Precision": precision_scores
})

results.sort_values(by="Precision", ascending=False)

,Model,Accuracy,Precision
9,KNN,0.911877,1.000000
3,Bernoulli NB,0.979885,0.991803
10,SVC,0.976054,0.983333
2,Multinomial NB,0.974138,0.983051
5,Random Forest,0.976054,0.975410
0,Logistic Regression,0.956897,0.970588
6,Extra Trees,0.976054,0.953125
8,Gradient Boosting,0.955939,0.927928
7,AdaBoost,0.915709,0.819277
4,Decision Tree,0.936782,0.755102


In [53]:
import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(bn,open('model.pkl','wb'))