In [2]:
import string
from unittest.mock import inplace

import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from pygments.styles.dracula import background
from sklearn.conftest import pytest_generate_tests
from sympy import vectorize

In [3]:
data=pd.read_csv('spam.csv',encoding='latin-1')
data.sample(10)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
4375,spam,"If you don't, your prize will go to another cu...",NaN,NaN,NaN
3459,ham,I am back. Bit long cos of accident on a30. Ha...,NaN,NaN,NaN
5040,ham,She ran off with a younger man. we will make p...,NaN,NaN,NaN
4659,ham,You call him and tell now infront of them. Cal...,NaN,NaN,NaN
1329,ham,I dont know what to do to come out of this so ...,NaN,NaN,NaN
3252,ham,K:)k..its good:)when are you going?,NaN,NaN,NaN
1036,ham,"No my blankets are sufficient, thx",NaN,NaN,NaN
754,ham,Realy sorry-i don't recognise this number and ...,NaN,NaN,NaN
3652,ham,It has issues right now. Ill fix for her by to...,NaN,NaN,NaN
2717,ham,Okie.. Thanx..,NaN,NaN,NaN


In [4]:
data.info()
data=data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [5]:
data.rename(columns={'v1':'target','v2':'text'},inplace=True)

In [6]:
data['target'].unique()

array(['ham', 'spam'], dtype=object)

In [7]:
data['target']=data['target'].map({'ham':0,'spam':1})

In [8]:
data.head()

,target,text
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [90]:
import random

subjects = [
    "Congratulations", "URGENT", "Dear user", "Alert", "Limited time offer",
    "Exclusive deal", "Important notice", "Final reminder"
]

actions = [
    "you have won", "you are selected for", "claim your", "get your",
    "verify your", "update your", "unlock your", "activate your"
]

objects = [
    "lottery prize", "free car", "cash reward", "iPhone", "gift voucher",
    "bank account", "KYC details", "OTP verification", "delivery package"
]

values = [
    "₹10,000", "₹50,000", "₹1 lakh", "₹25 lakh", "free", "exclusive"
]

endings = [
    "now", "immediately", "today", "before expiry", "limited time",
    "click here", "act fast", "don’t miss this"
]

templates = [
    "{s}! {a} a {v} {o}. {e}",
    "{s}: {a} your {o} {e}",
    "{s}! {a} {o}. {e}",
    "{s}, {a} {v} {o} {e}",
]

def generate_spam(n=1000):
    spam_list = []
    for _ in range(n):
        msg = random.choice(templates).format(
            s=random.choice(subjects),
            a=random.choice(actions),
            v=random.choice(values),
            o=random.choice(objects),
            e=random.choice(endings)
        )
        spam_list.append(msg)
    return spam_list

spam_messages = generate_spam(1000)
spam_messages

['Final reminder! unlock your iPhone. don’t miss this',
 'Congratulations: claim your your OTP verification click here',
 'Final reminder: get your your gift voucher now',
 'Dear user: unlock your your OTP verification today',
 'Congratulations! claim your a free OTP verification. immediately',
 'Exclusive deal! get your free car. act fast',
 'Alert, activate your ₹1 lakh lottery prize before expiry',
 'Final reminder, you have won ₹1 lakh cash reward limited time',
 'Final reminder! update your a ₹1 lakh cash reward. act fast',
 'Exclusive deal! you have won free car. before expiry',
 'Final reminder: update your your delivery package click here',
 'Exclusive deal! you have won a free KYC details. don’t miss this',
 'Important notice! get your OTP verification. don’t miss this',
 'URGENT: you are selected for your bank account click here',
 'Exclusive deal! activate your KYC details. act fast',
 'URGENT: you have won your OTP verification limited time',
 'Important notice! claim your 

In [92]:
new_df=pd.DataFrame({
    'text':spam_messages,
    'target':[1]*len(spam_messages)
})
new_df

,text,target
0,Final reminder! unlock your iPhone. don’t miss...,1
1,Congratulations: claim your your OTP verificat...,1
2,Final reminder: get your your gift voucher now,1
3,Dear user: unlock your your OTP verification t...,1
4,Congratulations! claim your a free OTP verific...,1
...,...,...
995,Exclusive deal: you have won your iPhone limit...,1
996,Limited time offer: activate your your iPhone ...,1
997,Exclusive deal: you are selected for your OTP ...,1
998,Exclusive deal! update your cash reward. now,1


In [93]:
data=pd.concat([data,new_df],ignore_index=True)
data=data.sample(frac=1,random_state=42).reset_index(drop=True)
data.tail(10)

,target,text,num_char,num_words,num_sen,transformed_text
6209,0,Are you staying in town ?,25.0,6.0,1.0,staying town
6210,1,Congratulations! claim your a free KYC details...,NaN,NaN,NaN,NaN
6211,0,Most of the tiime when i don't let you hug me ...,79.0,22.0,1.0,tiime let hug break tears
6212,1,Important notice: you have won your OTP verifi...,NaN,NaN,NaN,NaN
6213,0,Hi its Kate how is your evening? I hope i can ...,131.0,34.0,4.0,hi kate evening hope see tomorrow bit bloody b...
6214,0,say thanks2.,13.0,3.0,1.0,say thanks2
6215,0,Well that must be a pain to catch,33.0,8.0,1.0,well must pain catch
6216,1,"Final reminder, you have won ₹1 lakh cash rewa...",NaN,NaN,NaN,NaN
6217,1,Important notice: unlock your your iPhone act ...,NaN,NaN,NaN,NaN
6218,0,Yeah you should. I think you can use your gt a...,159.0,40.0,4.0,yeah think use gt atm register sure anyway hel...


In [94]:
data.isna().sum()

target                 0
text                   0
num_char            1000
num_words           1000
num_sen             1000
transformed_text    1000
dtype: int64

In [95]:
#Checking duplicates
data.duplicated().sum()

np.int64(16)

In [96]:
data=data.drop_duplicates(keep='first')
data.shape

(6203, 6)

In [16]:
#EDA
!pip install matplotlib


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----------- ---------------------------- 2.4/8.1 MB 16.8 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 21.0 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 19.7 MB/s  0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 14.8 MB/s  0:00:00

   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------- ------------------------------- 1/5 [fonttools]
   -------------------------------- ------- 4/5 [matplotlib]
   -------------------------------- ------- 4/5 [matplotlib]
   --------------


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [97]:
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
# cnt=data['target'].value_counts()
# percentage=(cnt/(len(cnt)))*100
# plot=data['target'].value_counts(normalize=True).plot(kind='bar')
# for ind,val in enumerate(percentage):
#     plot.text(ind,cnt.values[ind]+0.1,f"{val:.2f}%",ha='center')
# plt.show()
cnt = data['target'].value_counts()
percentage = cnt / len(data) * 100

ax = cnt.plot(kind='bar')

for i, v in enumerate(cnt):
    ax.text(i, v + 0.1, f"{percentage.iloc[i]:.2f}%", ha='center')

plt.title("Target Distribution")
plt.xlabel("Target")
plt.ylabel("Count")

plt.show()


In [98]:
import matplotlib.pyplot as plt
plt.pie(cnt,labels=['not spam','spam'],autopct='%0.2f')
plt.show()

In [22]:
!pip install nltk


   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------- ----- 1.3/1.5 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 10.8 MB/s  0:00:00

   ------------- -------------------------- 1/3 [click]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]




[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [22]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\palla\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [99]:
data['num_char']=data['text'].apply(len)
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,I am getting threats from your sales executive...,113,21.0,2.0,getting threats sales executive shifad raised ...
1,0,R u saying i should re order the slippers cos ...,76,18.0,1.0,r u saying order slippers cos pay returning
2,0,"Ya, i'm referin to mei's ex wat... No ah, wait...",139,39.0,1.0,ya referin mei ex wat ah waitin 4 u treat some...
3,1,Final reminder: activate your your gift vouche...,56,NaN,NaN,NaN
4,0,Ard 4 lor...,12,4.0,1.0,ard 4 lor


In [100]:
data['num_words']=data['text'].apply(lambda x:len(nltk.word_tokenize(x)))
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,I am getting threats from your sales executive...,113,21,2.0,getting threats sales executive shifad raised ...
1,0,R u saying i should re order the slippers cos ...,76,18,1.0,r u saying order slippers cos pay returning
2,0,"Ya, i'm referin to mei's ex wat... No ah, wait...",139,39,1.0,ya referin mei ex wat ah waitin 4 u treat some...
3,1,Final reminder: activate your your gift vouche...,56,10,NaN,NaN
4,0,Ard 4 lor...,12,4,1.0,ard 4 lor


In [101]:
data['num_sen']=data['text'].apply(lambda x:len(nltk.sent_tokenize(x)))
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,I am getting threats from your sales executive...,113,21,2,getting threats sales executive shifad raised ...
1,0,R u saying i should re order the slippers cos ...,76,18,1,r u saying order slippers cos pay returning
2,0,"Ya, i'm referin to mei's ex wat... No ah, wait...",139,39,1,ya referin mei ex wat ah waitin 4 u treat some...
3,1,Final reminder: activate your your gift vouche...,56,10,1,NaN
4,0,Ard 4 lor...,12,4,1,ard 4 lor


In [102]:
#For not spam
data[data['target']==0][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,4516.000000,4516.000000,4516.000000
mean,70.459256,17.123782,1.820195
std,56.358207,13.493970,1.383657
min,2.000000,1.000000,1.000000
25%,34.000000,8.000000,1.000000
50%,52.000000,13.000000,1.000000
75%,90.000000,22.000000,2.000000
max,910.000000,220.000000,38.000000


In [103]:
#For spam
data[data['target']==1][['num_char','num_words','num_sen']].describe()

,num_char,num_words,num_sen
count,1687.000000,1687.000000,1687.000000
mean,87.105513,17.250741,2.394191
std,44.986628,9.472973,1.289354
min,13.000000,2.000000,1.000000
25%,53.000000,10.000000,1.000000
50%,62.000000,12.000000,3.000000
75%,140.000000,27.000000,3.000000
max,224.000000,46.000000,9.000000


In [38]:
!pip install seaborn


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [104]:
import seaborn as sns
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_words'],color='green')
sns.histplot(data[data['target']==1]['num_words'],color='red')

plt.show()

In [105]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_char'],color='green')
sns.histplot(data[data['target']==1]['num_char'],color='red')
plt.show()

In [106]:
plt.figure(figsize=(12,6))
sns.histplot(data[data['target']==0]['num_sen'],color='green')
sns.histplot(data[data['target']==1]['num_sen'],color='red')
plt.show()

In [107]:
sns.heatmap(data[['target','num_char','num_words','num_sen']].corr(),annot=True)
plt.show()

Text Preprocessing

In [32]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [108]:
import string
def text_tranform(text):
    text=text.lower()
    text=nltk.word_tokenize(text)
    res=[]
    for i in text:
        if i.isalnum():
            res.append(i)
    text=res[:]
    res.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            res.append(i)
    text=res[:]
    # res.clear()
    # for i in text:
    #     res.append(ps.stem(i))
    return ' '.join(res)

In [109]:
data['transformed_text']=data['text'].apply(text_tranform)

In [110]:
data.head()

,target,text,num_char,num_words,num_sen,transformed_text
0,0,I am getting threats from your sales executive...,113,21,2,getting threats sales executive shifad raised ...
1,0,R u saying i should re order the slippers cos ...,76,18,1,r u saying order slippers cos pay returning
2,0,"Ya, i'm referin to mei's ex wat... No ah, wait...",139,39,1,ya referin mei ex wat ah waitin 4 u treat some...
3,1,Final reminder: activate your your gift vouche...,56,10,1,final reminder activate gift voucher act fast
4,0,Ard 4 lor...,12,4,1,ard 4 lor


In [86]:
!pip install wordcloud


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [111]:
from wordcloud import WordCloud
wc=WordCloud(width=1000,height=1000,background_color='beige')


In [112]:
spam_wc=wc.generate(data[data['target']==0]['transformed_text'].str.cat(sep=" "))

In [113]:
plt.imshow(spam_wc)
plt.show()

In [114]:
ham_wc=wc.generate(data[data['target']==1]['transformed_text'].str.cat(sep=" "))

In [115]:
plt.imshow(ham_wc)
plt.show()

In [116]:
from collections import Counter
ham_corpus=[]
for sen in data[data['target']==0]['transformed_text'].to_list():
    for word in sen.split():
        ham_corpus.append(word)
word_count=Counter(ham_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='magma',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

In [117]:
spam_corpus=[]
for sen in data[data['target']==1]['transformed_text'].to_list():
    for word in sen.split():
        spam_corpus.append(word)
word_count=Counter(spam_corpus).most_common(30)
sns.barplot(x=pd.DataFrame(word_count)[0],y=pd.DataFrame(word_count)[1],palette='flare',legend=False,hue=pd.DataFrame(word_count)[0])
plt.xticks(rotation='vertical')
plt.show()

Model

In [118]:
print(text_tranform('congratulation you won a car in lucky draw'))

congratulation car lucky draw


In [119]:
#Using bag of words vectorization method
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer()
vectorizer=TfidfVectorizer(ngram_range=(1,2),max_features=4000)

In [120]:
X=vectorizer.fit_transform(data['transformed_text']).toarray()
X.shape


(6203, 4000)

In [121]:
features = vectorizer.get_feature_names_out()

print("lucky draw" in features)  # should be True
print("won car" in features)    # should be True

True
False


In [122]:
Y=data['target'].values
Y

array([0, 0, 0, ..., 1, 1, 0], shape=(6203,))

In [123]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [124]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix
gn=GaussianNB()
mn=MultinomialNB()
bn=BernoulliNB()


In [125]:
gn.fit(X_train,Y_train)
y_pred1=gn.predict(X_test)
print(accuracy_score(Y_test,y_pred1))
print(precision_score(Y_test,y_pred1))
print(confusion_matrix(Y_test,y_pred1))


0.9250604351329573
0.800498753117207
[[827  80]
 [ 13 321]]


In [126]:
mn.fit(X_train,Y_train)
y_pred2=mn.predict(X_test)
print(accuracy_score(Y_test,y_pred2))
print(precision_score(Y_test,y_pred2))
print(confusion_matrix(Y_test,y_pred2))


0.9790491539081386
0.9935897435897436
[[905   2]
 [ 24 310]]


In [127]:
bn.fit(X_train,Y_train)
y_pred3=bn.predict(X_test)
print(accuracy_score(Y_test,y_pred3))
print(precision_score(Y_test,y_pred3))
print(confusion_matrix(Y_test,y_pred3))


0.9798549556809025
1.0
[[907   0]
 [ 25 309]]


In [128]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [129]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Gaussian NB": GaussianNB(),
    "Multinomial NB": MultinomialNB(),
    "Bernoulli NB": BernoulliNB(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Extra Trees": ExtraTreesClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC()
}
def train_model(model, X_train, Y_train, X_test, Y_test):

    model.fit(X_train, Y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(Y_test, y_pred)
    prec = precision_score(Y_test, y_pred)

    return acc, prec
accuracy_scores = []
precision_scores = []
model_names = []

for name, model in models.items():

    acc, prec = train_model(model, X_train, Y_train, X_test, Y_test)

    model_names.append(name)
    accuracy_scores.append(acc)
    precision_scores.append(prec)
    results = pd.DataFrame({
    "Model": model_names,
    "Accuracy": accuracy_scores,
    "Precision": precision_scores
})

results.sort_values(by="Precision", ascending=False)

,Model,Accuracy,Precision
9,KNN,0.905721,1.000000
10,SVC,0.981467,1.000000
3,Bernoulli NB,0.979855,1.000000
0,Logistic Regression,0.967768,0.996622
2,Multinomial NB,0.979049,0.993590
6,Extra Trees,0.982272,0.984472
5,Random Forest,0.978243,0.984227
8,Gradient Boosting,0.955681,0.982699
7,AdaBoost,0.821918,0.895105
4,Decision Tree,0.949234,0.886040


In [131]:
import pickle
pickle.dump(tfidf,open('vectorizer.pkl','wb'))
pickle.dump(SVC,open('model.pkl','wb'))